version: "3"
services:
  pyspark-notebook:
    image: jupyter/pyspark-notebook
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - ".:/home/jovyan/work"
    environment:
      - JUPYTER_ENABLE_LAB=yes
